
export default new Map([
["src/content/blog/ai-gateway-vs-api-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fai-gateway-vs-api-gateway.mdx&astroContentModuleFlag=true")],
["src/content/blog/how-to-rate-limit-openai-access-in-kubernetes-using-envoy-ai-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhow-to-rate-limit-openai-access-in-kubernetes-using-envoy-ai-gateway.mdx&astroContentModuleFlag=true")],
["src/content/blog/secure-hugging-face-tgi-with-envoy-ai-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsecure-hugging-face-tgi-with-envoy-ai-gateway.mdx&astroContentModuleFlag=true")],
["src/content/blog/secure-scalable-ai-inference-for-kubernetes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsecure-scalable-ai-inference-for-kubernetes.mdx&astroContentModuleFlag=true")],
["src/content/blog/tutorial-02-track-and-limit-llm-token-usage-in-langchain-with-envoy-ai-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftutorial-02-track-and-limit-llm-token-usage-in-langchain-with-envoy-ai-gateway.mdx&astroContentModuleFlag=true")],
["src/content/blog/what-is-an-ai-gateway-and-why-do-you-need-one.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fwhat-is-an-ai-gateway-and-why-do-you-need-one.mdx&astroContentModuleFlag=true")],
["src/content/blog/tutorial-01-enforce-oidc-auth-for-openai-with-envoy-ai-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftutorial-01-enforce-oidc-auth-for-openai-with-envoy-ai-gateway.mdx&astroContentModuleFlag=true")],
["src/content/blog/tutorial-03-protect-internal-model-apis-seldon-bentoml-with-mtls-in-envoy-gateway.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftutorial-03-protect-internal-model-apis-seldon-bentoml-with-mtls-in-envoy-gateway.mdx&astroContentModuleFlag=true")]]);
		